nama = input("Nama Lengkap: ")
ttl = input("TTL: ")
alamat = input("Alamat: ")
nomor = input("No. Hp: ")
prodi = input("Program Study: ")
hobi = input("Hobi: ")
print("Nama lengkap: " + nama)
print("TTL: " + ttl)
print("Alamat: " + alamat)
print("No. Hp: " + nomor)
print("Program Study: " + prodi)
print("Hobi: " + hobi)